print("DDDD               SSSSSSSSS       MMM         MMM   ")
print(" D  DD           SS                 MMM       M MM   ")
print(" D    DD        SS                  MM M     M  MM   ")
print(" D      DD      SS                  MM  M   M   MM   ")
print(" D      DD       SS                 MM   M M    MM   ")
print(" D      DD         SSSSSSSS         MM    M     MM   ")
print(" D      DD                 SS       MM          MM   ")
print(" D      DD                  SS      MM          MM   ")
print(" D    DD                    SS      MM          MM   ")
print(" D  DD                     SS       MM          MM   ")
print("DDDD              SSSSSSSSS        MMMM        MMMM  ")